name: test

on:
  push

env:
  FORCE_COLOR: 1

jobs:
  windows:
    runs-on: windows-latest
    strategy:
      matrix:
        node: [14]
        electron: [8, 10]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm install electron@${{ matrix.electron }}
      - run: npm test
  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        node: [12]
        electron: [9, 10]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm install electron@${{ matrix.electron }}
      - run: npm test
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10]
        electron: [8, 9]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm install electron@${{ matrix.electron }}
      - name: Run npm test
        run: xvfb-run --auto-servernum npm test
